# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# collections:
collections:
  projects:
    output: true
    permalink: /projects/:path/



# Site settings
title: Adrian
email: adrian.mui@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  personal website for blogging, code publishing, and self-advertising
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adrianmui.github.io" # the base hostname & protocol for your site
twitter_username: qwertyzone
github_username:  adrianmui

# Build settings
markdown: kramdown
